# 캘리포니아 주택 가격 예측
| 변수명 | 설명 | 데이터타입 |
|----------|------------|-----|
| longitude| 경도	| Continuous |
| latitude | 위도   | Continuous |
| housingmedianage | 주택나이(중앙값) | Continuous |
| total_rooms | 전체 방 수 | Continuous |
| total_bedrooms | 전체 침실 수 | Continuous |
| population | 인구 | Continuous |
| households | 세대 수 | Continuous |
| median_income | 소득(중앙값) | Continuous |
| **medianhousevalue** | 주택 가치(중앙값) | Continuous |
| ocean_proximity | 바다 근접도 | Categorical |

In [136]:
# 모듈 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') # 경고창 무시

In [137]:
# housing.csv를 읽어 df에 저장하세요.
df = pd.read_csv('./sample_data/housing.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [138]:
# 데이터 프레임의 상위 20개를 조회하세요.
df.head(20)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0,NEAR BAY
11,-122.26,37.85,52.0,3503.0,752.0,1504.0,734.0,3.2705,241800.0,NEAR BAY
12,-122.26,37.85,52.0,2491.0,474.0,1098.0,468.0,3.0750,213500.0,NEAR BAY
13,-122.26,37.84,52.0,696.0,191.0,345.0,174.0,2.6736,191300.0,NEAR BAY
14,-122.26,37.85,52.0,2643.0,626.0,1212.0,620.0,1.9167,159200.0,NEAR BAY
15,-122.26,37.85,50.0,1120.0,283.0,697.0,264.0,2.1250,140000.0,NEAR BAY
16,-122.27,37.85,52.0,1966.0,347.0,793.0,331.0,2.7750,152500.0,NEAR BAY
17,-122.27,37.85,52.0,1228.0,293.0,648.0,303.0,2.1202,155500.0,NEAR BAY
18,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911,158700.0,NEAR BAY
19,-122.27,37.84,52.0,1503.0,298.0,690.0,275.0,2.6033,162900.0,NEAR BAY

In [139]:
# 데이터 프레임의 shape을 확인하세요.
df.shape

(20640, 10)

In [140]:
# 데이터 프레임의 정보를 확인하세요.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [141]:
# 각 컬럼별 결측치의 개수를 조회하세요.
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [142]:
# 각 컬럼별 결측치의 비율를 조회하세요.
# 비율 = 결측치 / 전체 데이터
df.isna().sum()/(df.count()+df.isna().sum())

longitude             0.000000
latitude              0.000000
housing_median_age    0.000000
total_rooms           0.000000
total_bedrooms        0.010029
population            0.000000
households            0.000000
median_income         0.000000
median_house_value    0.000000
ocean_proximity       0.000000
dtype: float64

In [143]:
# 결측치가 존재하는 행 정보를 확인하세요.
df[df['total_bedrooms'].isna()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
290,-122.16,37.77,47.0,1256.0,NaN,570.0,218.0,4.3750,161900.0,NEAR BAY
341,-122.17,37.75,38.0,992.0,NaN,732.0,259.0,1.6196,85100.0,NEAR BAY
538,-122.28,37.78,29.0,5154.0,NaN,3741.0,1273.0,2.5762,173400.0,NEAR BAY
563,-122.24,37.75,45.0,891.0,NaN,384.0,146.0,4.9489,247100.0,NEAR BAY
696,-122.10,37.69,41.0,746.0,NaN,387.0,161.0,3.9063,178400.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20267,-119.19,34.20,18.0,3620.0,NaN,3171.0,779.0,3.3409,220500.0,NEAR OCEAN
20268,-119.18,34.19,19.0,2393.0,NaN,1938.0,762.0,1.6953,167400.0,NEAR OCEAN
20372,-118.88,34.17,15.0,4260.0,NaN,1701.0,669.0,5.1033,410700.0,<1H OCEAN
20460,-118.75,34.29,17.0,5512.0,NaN,2734.0,814.0,6.6073,258100.0,<1H OCEAN
20484,-118.72,34.28,17.0,3051.0,NaN,1705.0,495.0,5.7376,218600.0,<1H OCEAN

In [144]:
# total_bedrooms의 중앙값으로 결측치를 대체하세요.
df['total_bedrooms'].fillna(df['total_bedrooms'].median(),inplace=True)

# 결측치가 존재하는지 확인하세요.
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [145]:
# 코드를 실행하세요.
## continuous 변수와 categorical 변수를 생성하세요.
# continuous : continuous type의 컬럼명이 담긴 리스트
# categorical : categorical type의 컬럼명이 담긴 리스트
continuous = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']
categorical = ['ocean_proximity']

In [146]:
# 범주형 컬럼인 ocean_proximity의 범주별 개수를 계산하세요.
df['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [147]:
# 범주형 컬럼인 ocean_proximity의 범주별 비율을 계산하세요.
df['ocean_proximity'].value_counts()/df['ocean_proximity'].count()

<1H OCEAN     0.442636
INLAND        0.317393
NEAR OCEAN    0.128779
NEAR BAY      0.110950
ISLAND        0.000242
Name: ocean_proximity, dtype: float64

In [148]:
# ocean_proximity 컬럼의 <1H OCEAN 값을 1H OCEAN으로 수정하세요
# < 기호를 제거합니다.
cond = df['ocean_proximity'] == '<1H OCEAN'
df.loc[cond,'ocean_proximity'] = '1H OCEAN'

In [149]:
# 범주형 컬럼인 ocean_proximity의 범주별 비율을 재계산하세요.
df['ocean_proximity'].value_counts()/df['ocean_proximity'].count()

1H OCEAN      0.442636
INLAND        0.317393
NEAR OCEAN    0.128779
NEAR BAY      0.110950
ISLAND        0.000242
Name: ocean_proximity, dtype: float64

In [150]:
# 코드를 실행하세요.
## 아래 컬럼은 log 변환을 적용해주세요.
# total_rooms, total_bedrooms, population, households, median_income, median_house_value
target_col = 'total_rooms, total_bedrooms, population, households, median_income, median_house_value'.split(', ')
for col_name in target_col:
    df[col_name] = np.log1p(df[col_name])

In [151]:
# continuous 컬럼을 표준화하세요. (StandardScaler)
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
tmp = df['ocean_proximity']
df.drop('ocean_proximity',axis=1,inplace=True)
df = pd.DataFrame(ss.fit_transform(df),columns=['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'])
df = pd.concat([df,tmp],axis=1)

df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-1.327835,1.052548,0.982143,-1.131133,-1.642192,-1.694943,-1.569395,1.995505,1.647949,NEAR BAY
1,-1.322844,1.043185,-0.607019,1.651357,1.320043,1.030337,1.449251,1.988380,1.238403,NEAR BAY
2,-1.332827,1.038503,1.856182,-0.450310,-1.110094,-1.109604,-1.104849,1.656444,1.206751,NEAR BAY
3,-1.337818,1.038503,1.856182,-0.638257,-0.817506,-0.949925,-0.813343,1.049948,1.152012,NEAR BAY
4,-1.337818,1.038503,1.856182,-0.312370,-0.576140,-0.933021,-0.583469,0.170631,1.156639,NEAR BAY

In [152]:
# pd.get_dummies 함수를 이용하여 범주형 컬럼에 One Hot 변환을 적용하세요.
df = pd.get_dummies(df, columns = ['ocean_proximity'])
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-1.327835,1.052548,0.982143,-1.131133,-1.642192,-1.694943,-1.569395,1.995505,1.647949,0,0,0,1,0
1,-1.322844,1.043185,-0.607019,1.651357,1.320043,1.030337,1.449251,1.988380,1.238403,0,0,0,1,0
2,-1.332827,1.038503,1.856182,-0.450310,-1.110094,-1.109604,-1.104849,1.656444,1.206751,0,0,0,1,0
3,-1.337818,1.038503,1.856182,-0.638257,-0.817506,-0.949925,-0.813343,1.049948,1.152012,0,0,0,1,0
4,-1.337818,1.038503,1.856182,-0.312370,-0.576140,-0.933021,-0.583469,0.170631,1.156639,0,0,0,1,0

In [153]:
## X, y를 분리하세요.
# X : median_house_value 컬럼을 제외한 나머지 컬럼
# y : median_house_value 컬럼
X = df.drop('median_house_value',axis=1)
y = df['median_house_value']

X.shape, y.shape

((20640, 13), (20640,))

In [154]:
# X와 Y를 학습데이터와 검증데이터로 분리하세요.
# random_state = 0
from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(
    X, y, random_state=0
)

In [157]:
# DNN 모델을 생성하세요. (회귀 모델)
import tensorflow as tf
from tensorflow.keras import models,layers
model = models.Sequential() 
model.add(layers.Dense(256, activation='relu'
               , input_shape=(x_tr.shape[1],)))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(1))     # 마지막 Dense의 activation 생략(linear기본), unit 기본 1

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 256)               3584

 dense_11 (Dense)            (None, 256)               65792

 dense_12 (Dense)            (None, 256)               65792

 dense_13 (Dense)            (None, 256)               65792

 dense_14 (Dense)            (None, 1)                 257

=================================================================
Total params: 201,217
Trainable params: 201,217
Non-trainable params: 0
_________________________________________________________________

In [161]:
# 컴파일(compile)
# loss : mean absolute error, optimizer : adam, metrics : mean squared error
model.compile(optimizer='adam', loss='mae',metrics=['mse'])

In [180]:
# 학습(fit)
history = model.fit(x_tr, y_tr ,epochs =100, batch_size=25, validation_split=0.2)
model.evaluate(x_te, y_te)

Epoch 1/100
496/496 [==============================] - 4s 7ms/step - loss: 0.1177 - mse: 0.0310 - val_loss: 0.1939 - val_mse: 0.0791
Epoch 2/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1152 - mse: 0.0292 - val_loss: 0.1969 - val_mse: 0.0838
Epoch 3/100
496/496 [==============================] - 3s 6ms/step - loss: 0.1156 - mse: 0.0298 - val_loss: 0.1957 - val_mse: 0.0807
Epoch 4/100
496/496 [==============================] - 4s 8ms/step - loss: 0.1134 - mse: 0.0284 - val_loss: 0.1965 - val_mse: 0.0813
Epoch 5/100
496/496 [==============================] - 4s 7ms/step - loss: 0.1127 - mse: 0.0279 - val_loss: 0.1984 - val_mse: 0.0819
Epoch 6/100
496/496 [==============================] - 3s 6ms/step - loss: 0.1124 - mse: 0.0280 - val_loss: 0.1977 - val_mse: 0.0829
Epoch 7/100
496/496 [==============================] - 3s 7ms/step - loss: 0.1111 - mse: 0.0277 - val_loss: 0.2017 - val_mse: 0.0848
Epoch 8/100
496/496 [==============================] - 4s 8ms/step - loss: 0.1121 - mse: 0.0278 - val_loss: 0.2043 - val_mse: 0.0892
Epoch 9/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1129 - mse: 0.0280 - val_loss: 0.2005 - val_mse: 0.0840
Epoch 10/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1118 - mse: 0.0275 - val_loss: 0.1979 - val_mse: 0.0829
Epoch 11/100
496/496 [==============================] - 2s 5ms/step - loss: 0.1083 - mse: 0.0262 - val_loss: 0.2012 - val_mse: 0.0834
Epoch 12/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1106 - mse: 0.0270 - val_loss: 0.2007 - val_mse: 0.0846
Epoch 13/100
496/496 [==============================] - 4s 7ms/step - loss: 0.1109 - mse: 0.0271 - val_loss: 0.2102 - val_mse: 0.0921
Epoch 14/100
496/496 [==============================] - 4s 8ms/step - loss: 0.1090 - mse: 0.0260 - val_loss: 0.2037 - val_mse: 0.0850
Epoch 15/100
496/496 [==============================] - 4s 8ms/step - loss: 0.1079 - mse: 0.0258 - val_loss: 0.2043 - val_mse: 0.0872
Epoch 16/100
496/496 [==============================] - 2s 5ms/step - loss: 0.1077 - mse: 0.0256 - val_loss: 0.2016 - val_mse: 0.0860
Epoch 17/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1069 - mse: 0.0253 - val_loss: 0.2021 - val_mse: 0.0868
Epoch 18/100
496/496 [==============================] - 3s 6ms/step - loss: 0.1055 - mse: 0.0248 - val_loss: 0.2042 - val_mse: 0.0866
Epoch 19/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1071 - mse: 0.0254 - val_loss: 0.2060 - val_mse: 0.0883
Epoch 20/100
496/496 [==============================] - 3s 6ms/step - loss: 0.1056 - mse: 0.0245 - val_loss: 0.2045 - val_mse: 0.0875
Epoch 21/100
496/496 [==============================] - 3s 5ms/step - loss: 0.1053 - mse: 0.0247 - val_loss: 0.2016 - val_mse: 0.0885
Epoch 22/100
496/496 [==============================] - 2s 5ms/step - loss: 0.1028 - mse: 0.0232 - val_loss: 0.2038 - val_mse: 0.0868
Epoch 23/100
496/496 [==============================] - 2s 5ms/step - loss: 0.1041 - mse: 0.0244 - val_loss: 0.2102 - val_mse: 0.0928
Epoch 24/100
496/496 [==============================] - 4s 7ms/step - loss: 0.1046 - mse: 0.0240 - val_loss: 0.2063 - val_mse: 0.0903
Epoch 25/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1032 - mse: 0.0240 - val_loss: 0.2101 - val_mse: 0.0912
Epoch 26/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1021 - mse: 0.0235 - val_loss: 0.2098 - val_mse: 0.0918
Epoch 27/100
496/496 [==============================] - 2s 5ms/step - loss: 0.1027 - mse: 0.0235 - val_loss: 0.2045 - val_mse: 0.0893
Epoch 28/100
496/496 [==============================] - 3s 6ms/step - loss: 0.1009 - mse: 0.0225 - val_loss: 0.2096 - val_mse: 0.0936
Epoch 29/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1016 - mse: 0.0230 - val_loss: 0.2032 - val_mse: 0.0884
Epoch 30/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1006 - mse: 0.0223 - val_loss: 0.2080 - val_mse: 0.0899
Epoch 31/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1002 - mse: 0.0224 - val_loss: 0.2103 - val_mse: 0.0921
Epoch 32/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0991 - mse: 0.0219 - val_loss: 0.2134 - val_mse: 0.0938
Epoch 33/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1011 - mse: 0.0229 - val_loss: 0.2111 - val_mse: 0.0942
Epoch 34/100
496/496 [==============================] - 2s 4ms/step - loss: 0.1008 - mse: 0.0221 - val_loss: 0.2105 - val_mse: 0.0939
Epoch 35/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0990 - mse: 0.0219 - val_loss: 0.2098 - val_mse: 0.0945
Epoch 36/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0994 - mse: 0.0221 - val_loss: 0.2102 - val_mse: 0.0912
Epoch 37/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0994 - mse: 0.0216 - val_loss: 0.2107 - val_mse: 0.0935
Epoch 38/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0993 - mse: 0.0218 - val_loss: 0.2133 - val_mse: 0.0957
Epoch 39/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0990 - mse: 0.0217 - val_loss: 0.2164 - val_mse: 0.0957
Epoch 40/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0981 - mse: 0.0212 - val_loss: 0.2182 - val_mse: 0.0978
Epoch 41/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0969 - mse: 0.0209 - val_loss: 0.2102 - val_mse: 0.0934
Epoch 42/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0958 - mse: 0.0203 - val_loss: 0.2137 - val_mse: 0.0944
Epoch 43/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0969 - mse: 0.0211 - val_loss: 0.2201 - val_mse: 0.1014
Epoch 44/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0972 - mse: 0.0213 - val_loss: 0.2167 - val_mse: 0.0967
Epoch 45/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0959 - mse: 0.0202 - val_loss: 0.2097 - val_mse: 0.0929
Epoch 46/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0955 - mse: 0.0203 - val_loss: 0.2169 - val_mse: 0.0985
Epoch 47/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0953 - mse: 0.0197 - val_loss: 0.2156 - val_mse: 0.0988
Epoch 48/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0963 - mse: 0.0202 - val_loss: 0.2135 - val_mse: 0.0959
Epoch 49/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0944 - mse: 0.0198 - val_loss: 0.2168 - val_mse: 0.0973
Epoch 50/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0940 - mse: 0.0194 - val_loss: 0.2184 - val_mse: 0.1006
Epoch 51/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0945 - mse: 0.0197 - val_loss: 0.2180 - val_mse: 0.0989
Epoch 52/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0936 - mse: 0.0192 - val_loss: 0.2192 - val_mse: 0.1014
Epoch 53/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0942 - mse: 0.0195 - val_loss: 0.2164 - val_mse: 0.0989
Epoch 54/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0942 - mse: 0.0197 - val_loss: 0.2200 - val_mse: 0.1022
Epoch 55/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0928 - mse: 0.0188 - val_loss: 0.2169 - val_mse: 0.0989
Epoch 56/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0939 - mse: 0.0194 - val_loss: 0.2226 - val_mse: 0.1062
Epoch 57/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0935 - mse: 0.0192 - val_loss: 0.2187 - val_mse: 0.1020
Epoch 58/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0934 - mse: 0.0193 - val_loss: 0.2218 - val_mse: 0.1038
Epoch 59/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0925 - mse: 0.0185 - val_loss: 0.2224 - val_mse: 0.1055
Epoch 60/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0933 - mse: 0.0194 - val_loss: 0.2213 - val_mse: 0.1042
Epoch 61/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0914 - mse: 0.0187 - val_loss: 0.2199 - val_mse: 0.1027
Epoch 62/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0923 - mse: 0.0186 - val_loss: 0.2196 - val_mse: 0.1016
Epoch 63/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0914 - mse: 0.0185 - val_loss: 0.2220 - val_mse: 0.1044
Epoch 64/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0903 - mse: 0.0180 - val_loss: 0.2236 - val_mse: 0.1043
Epoch 65/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0906 - mse: 0.0182 - val_loss: 0.2190 - val_mse: 0.1000
Epoch 66/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0892 - mse: 0.0178 - val_loss: 0.2239 - val_mse: 0.1045
Epoch 67/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0908 - mse: 0.0183 - val_loss: 0.2214 - val_mse: 0.1039
Epoch 68/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0904 - mse: 0.0178 - val_loss: 0.2229 - val_mse: 0.1037
Epoch 69/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0891 - mse: 0.0176 - val_loss: 0.2243 - val_mse: 0.1055
Epoch 70/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0885 - mse: 0.0173 - val_loss: 0.2234 - val_mse: 0.1042
Epoch 71/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0892 - mse: 0.0175 - val_loss: 0.2196 - val_mse: 0.1011
Epoch 72/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0886 - mse: 0.0171 - val_loss: 0.2274 - val_mse: 0.1060
Epoch 73/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0878 - mse: 0.0174 - val_loss: 0.2232 - val_mse: 0.1052
Epoch 74/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0876 - mse: 0.0173 - val_loss: 0.2214 - val_mse: 0.1025
Epoch 75/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0881 - mse: 0.0172 - val_loss: 0.2257 - val_mse: 0.1062
Epoch 76/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0884 - mse: 0.0172 - val_loss: 0.2230 - val_mse: 0.1061
Epoch 77/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0864 - mse: 0.0165 - val_loss: 0.2268 - val_mse: 0.1081
Epoch 78/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0874 - mse: 0.0173 - val_loss: 0.2253 - val_mse: 0.1063
Epoch 79/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0868 - mse: 0.0165 - val_loss: 0.2262 - val_mse: 0.1051
Epoch 80/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0868 - mse: 0.0166 - val_loss: 0.2247 - val_mse: 0.1056
Epoch 81/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0864 - mse: 0.0163 - val_loss: 0.2328 - val_mse: 0.1118
Epoch 82/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0852 - mse: 0.0160 - val_loss: 0.2265 - val_mse: 0.1078
Epoch 83/100
496/496 [==============================] - 2s 5ms/step - loss: 0.0869 - mse: 0.0167 - val_loss: 0.2221 - val_mse: 0.1067
Epoch 84/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0848 - mse: 0.0162 - val_loss: 0.2316 - val_mse: 0.1116
Epoch 85/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0861 - mse: 0.0165 - val_loss: 0.2242 - val_mse: 0.1068
Epoch 86/100
496/496 [==============================] - 6s 12ms/step - loss: 0.0848 - mse: 0.0161 - val_loss: 0.2226 - val_mse: 0.1071
Epoch 87/100
496/496 [==============================] - 6s 11ms/step - loss: 0.0840 - mse: 0.0156 - val_loss: 0.2274 - val_mse: 0.1095
Epoch 88/100
496/496 [==============================] - 5s 10ms/step - loss: 0.0850 - mse: 0.0160 - val_loss: 0.2288 - val_mse: 0.1103
Epoch 89/100
496/496 [==============================] - 4s 8ms/step - loss: 0.0841 - mse: 0.0155 - val_loss: 0.2259 - val_mse: 0.1090
Epoch 90/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0843 - mse: 0.0158 - val_loss: 0.2282 - val_mse: 0.1096
Epoch 91/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0837 - mse: 0.0156 - val_loss: 0.2268 - val_mse: 0.1079
Epoch 92/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0843 - mse: 0.0155 - val_loss: 0.2283 - val_mse: 0.1110
Epoch 93/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0831 - mse: 0.0151 - val_loss: 0.2280 - val_mse: 0.1096
Epoch 94/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0837 - mse: 0.0155 - val_loss: 0.2287 - val_mse: 0.1098
Epoch 95/100
496/496 [==============================] - 2s 4ms/step - loss: 0.0843 - mse: 0.0156 - val_loss: 0.2279 - val_mse: 0.1127
Epoch 96/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0817 - mse: 0.0146 - val_loss: 0.2260 - val_mse: 0.1106
Epoch 97/100
496/496 [==============================] - 4s 8ms/step - loss: 0.0830 - mse: 0.0152 - val_loss: 0.2286 - val_mse: 0.1116
Epoch 98/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0852 - mse: 0.0164 - val_loss: 0.2321 - val_mse: 0.1122
Epoch 99/100
496/496 [==============================] - 3s 5ms/step - loss: 0.0824 - mse: 0.0149 - val_loss: 0.2280 - val_mse: 0.1092
Epoch 100/100
496/496 [==============================] - 3s 6ms/step - loss: 0.0814 - mse: 0.0148 - val_loss: 0.2291 - val_mse: 0.1118
162/162 [==============================] - 0s 2ms/step - loss: 0.3067 - mse: 0.1992

[0.30673378705978394, 0.1992247849702835]

In [184]:
# test 데이터에 대해 MSE, MAE, RMSE 오류를 계산합니다.
from sklearn.metrics import mean_absolute_error, mean_squared_error
pred = model.predict(x_te)
print('MAE :',mean_absolute_error(y_te,pred))
print('MSE :',mean_squared_error(y_te,pred))
print('RMSE :',np.sqrt(mean_squared_error(y_te,pred))) # MSE 결과에 np.sqrt 함수 적용

MAE : 0.30673375099550615
MSE : 0.1992248044021843
RMSE : 0.44634605901943875

In [185]:
# R Squared 결과도 확인합니다.
from sklearn.metrics import r2_score
print('R2 :',r2_score(y_te,pred))

R2 : 0.8013452967230528